name: $(SourceBranchName)-build$(Rev:.r)

trigger:
- ficzer

pool:
  name: dotNET

stages:
- stage: Build
  jobs:
  - job: BuildJob
    variables:
      solution: ProductGovernance.sln
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Debug'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node'
      inputs:
        versionSpec: '16.x' 

    - powershell: |
          cd Project1\ClientApp
          npm install --force
          node ./node_modules/react-scripts/bin/react-scripts.js build

    - task: NuGetToolInstaller@1
    
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

                